name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Compose
      run: |
          docker-compose build

    - name: Run Lint
      run: |
        pylint graphs

    - name: Run Tests
      run: |
        pytest