name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Compose
      run: |
        docker-compose up --build -d

    - name: Run Lint
      run: |
        docker-compose exec web pylint graphs

    - name: Run Tests
      run: |
        docker-compose exec web pytest