name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: spotsat
          POSTGRES_PASSWORD: spotsat
          POSTGRES_DB: graph_db

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Run Docker Compose
      run: |
        docker-compose up -d
        docker-compose exec web pytest
