name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker-compose up --build -d

    - name: Run tests
      run: docker-compose exec web pytest

    - name: Run pylint
      run: docker-compose exec web pylint graphs
